import { NgModule } from '@angular/core';
import {
    NgsAccordionModule,
    NgsAutoCompleteModule,
    NgsAvatarModule,
    NgsBadgeModule,
    NgsBarModule,
    NgsBreadcrumbsModule,
    NgsButtonModule,
    NgsCardModule,
    NgsChipModule,
    NgsDividerModule,
    NgsEmptyStateModule,
    NgsIconsModule,
    FormInputModule,
    NgsModalModule,
    NgsMenuModule,
    NgsNavModule,
    NgsPaginationModule,
    NgsPanelModule,
    NgsPopoverModule,
    NgsSpinnerModule,
    NgsStepModule,
    NgsTabModule,
    NgsTileModule,
    NgsToastModule,
    NgsToggleModule,
    NgsTooltipModule,
    TooltipModule,
} from 'angular-spectre';

const ngsModules = [
    NgsAccordionModule,
    NgsAutoCompleteModule,
    NgsAvatarModule,
    NgsBadgeModule,
    NgsBarModule,
    NgsBreadcrumbsModule,
    NgsButtonModule,
    NgsCardModule,
    NgsChipModule,
    NgsDividerModule,
    NgsEmptyStateModule,
    NgsIconsModule,
    FormInputModule,
    NgsModalModule,
    NgsMenuModule,
    NgsNavModule,
    NgsPaginationModule,
    NgsPanelModule,
    NgsPopoverModule,
    NgsSpinnerModule,
    NgsStepModule,
    NgsTabModule,
    NgsTileModule,
    NgsToastModule,
    NgsToggleModule,
    NgsTooltipModule,
    TooltipModule,
];

@NgModule({
    imports: ngsModules,
    exports: ngsModules
})
export class SharedModule { }
