export const routes = [
  { path: 'accordion', name: 'Accordion' },
  { path: 'auto-complete', name: 'Auto Complete' },
  { path: 'avatar', name: 'Avatar' },
  { path: 'badge', name: 'Badge' },
  { path: 'bar', name: 'Bars' },
  { path: 'breadcrumbs', name: 'Breadcrumbs' },
  { path: 'button', name: 'Button' },
  { path: 'card', name: 'Card' },
  { path: 'chip', name: 'Chip' },
  { path: 'empty-state', name: 'Empty State' },
  { path: 'form-input', name: 'Form Input' },
  { path: 'icons', name: 'Icons' },
  { path: 'modal', name: 'Modal' },
  { path: 'nav', name: 'Nav' },
  { path: 'pagination', name: 'Pagination' },
  { path: 'panel', name: 'Panel' },
  { path: 'popover', name: 'Popovers' },
  { path: 'step', name: 'Steps' },
  { path: 'tab', name: 'Tabs' },
  { path: 'tile', name: 'Tile' },
  { path: 'tooltip', name: 'Tooltip' },
  { path: 'tooltipBasic', name: 'Tooltip-Basic' },
];
