export const routes = [
  { path: 'accordion', name: 'Accordion'},
  { path: 'auto-complete', name: 'Auto Complete'},
  { path: 'avatar', name: 'Avatar'},
  { path: 'badge', name: 'Badge'},
  { path: 'breadcrumbs', name: 'Breadcrumbs'},
  { path: 'button', name: 'Button'},
  { path: 'card', name: 'Card'},
  { path: 'chip', name: 'Chip'},
  { path: 'empty-state', name: 'Empty State'},
  { path: 'form-input', name: 'Form Input'},
  { path: 'icons', name: 'Icons'},
  { path: 'pagination', name: 'Pagination'},
  { path: 'tooltip', name: 'Tooltip'},
  { path: 'tooltipBasic', name: 'Tooltip-Basic'},
  { path: 'modal', name: 'Modal'},
  { path: 'menu', name: 'Menu'},
  { path: 'toast', name: 'Toast'},
  { path: 'spinner', name: 'Spinner'}
];
